# Generated by Django 4.2.3 on 2023-09-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='user_image',
            field=models.ImageField(upload_to='base_statics/images/'),
        ),
    ]
