# Generated by Django 4.2.3 on 2023-09-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, upload_to='social_network/covers/profile/'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='user_image',
            field=models.ImageField(blank=True, default=None, upload_to='social_network/covers/'),
        ),
    ]
