# Generated by Django 4.2.3 on 2023-10-05 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_alter_profilepersonal_friend_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reverse_friend', to='social_network.profilepersonal')),
                ('user_reference', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.profilepersonal')),
            ],
        ),
    ]
