# Generated by Django 4.2.3 on 2023-09-26 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_network', '0002_alter_profilepersonal_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
