# Generated by Django 4.2.3 on 2023-09-30 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_alter_profilepersonal_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.publication'),
        ),
        migrations.AlterField(
            model_name='profilepersonal',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_network.status'),
        ),
    ]
