# Generated by Django 4.2.3 on 2023-10-06 00:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_network', '0003_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepersonal',
            name='friend_user',
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
        migrations.AddField(
            model_name='profilepersonal',
            name='friend_user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
