# Generated by Django 4.2.3 on 2023-09-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_alter_profilepersonal_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_video',
            field=models.FileField(blank=True, upload_to='social_network/covers/status/video'),
        ),
    ]
