# Generated by Django 4.2.3 on 2023-09-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_alter_profilepersonal_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonal',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='social_network/covers/profile/'),
        ),
    ]
