# Generated by Django 4.2.3 on 2023-09-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_profilepersonal_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepersonal',
            name='user_image',
            field=models.ImageField(blank=True, upload_to='social_network/covers/'),
        ),
    ]
