# Generated by Django 4.2.3 on 2023-10-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_remove_profilepersonal_friend_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepersonal',
            name='amigos',
            field=models.ManyToManyField(blank=True, to='social_network.profilepersonal'),
        ),
    ]
