# Generated by Django 4.2.3 on 2023-10-08 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_profilepersonal_amigos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepersonal',
            name='amigos',
        ),
        migrations.AlterField(
            model_name='status',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_status', to='social_network.profilepersonal'),
        ),
    ]
