# Generated by Django 4.2.3 on 2023-10-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
