# Generated by Django 4.2.3 on 2023-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0013_alter_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
