# Generated by Django 4.2.3 on 2023-11-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0015_post_likes_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_network/covers/post'),
        ),
    ]
