# Generated by Django 4.0 on 2023-11-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0016_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='social_network/covers/post/'),
        ),
    ]
