# Generated by Django 4.2.3 on 2024-03-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0018_notifications'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='notifications',
            managers=[
            ],
        ),
    ]
