# Generated by Django 4.2.3 on 2024-03-14 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0019_alter_notifications_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_notifications', to='social_network.profilepersonal'),
        ),
    ]
