# Generated by Django 4.2.3 on 2024-03-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0020_alter_notifications_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.CharField(default='Valor Padrão', max_length=255),
        ),
    ]
